export let allKeywords = $state({arr:[]});

export let kwFormat = $state({
    groupedOutput: true,
    labelOutput: true,
    uriOutput: true,
    pathOutput: false,
    detailed: true,
    specific: false,
    geonames: false
});

export function formatKeyword(label, uri){
    return ` ◍ ${kwFormat.labelOutput?label:''}${kwFormat.uriOutput?(' (' + (kwFormat.pathOutput?uri:uri.split('\/').pop()) + ')'):''}`
  }

export const atx = [
    ['hydrogeol', 'hydrogeology', 'https://data.geoscience.earth/ncl/geoera/keyword/2061'],
    ['geophys', 'geophysics', 'https://data.geoscience.earth/ncl/geoera/keyword/2066'],
    ['geotherm', 'geothermal energy', 'https://data.geoscience.earth/ncl/geoera/keyword/787'],
    ['seism', 'seismology', 'https://data.geoscience.earth/ncl/geoera/keyword/349'],
    ['geochemi', 'geochemistry', 'https://data.geoscience.earth/ncl/geoera/keyword/561'],
    ['marine geol', 'marine geology', 'https://data.geoscience.earth/ncl/geoera/keyword/2062']
  ];

export const country = [
  ['albania', 'Albania', 'https://sws.geonames.org/783754'],
  ['andorra', 'Andorra', 'https://sws.geonames.org/3041565'],
  ['armenia', 'Armenia', 'https://sws.geonames.org/174982'],
  ['austria', 'Austria', 'https://sws.geonames.org/2782113'],
  ['azerbaijan', 'Azerbaijan', 'https://sws.geonames.org/587116'],
  ['azores', 'Azores', 'https://sws.geonames.org/3411865'],
  ['bavaria', 'Bavaria', 'https://sws.geonames.org/2951839'],
  ['belarus', 'Belarus', 'https://sws.geonames.org/630336'],
  ['belgium', 'Belgium', 'https://sws.geonames.org/2802361'],
  ['bosnia', 'Bosnia and Herzegovina', 'https://sws.geonames.org/3277605'],
  ['bulgaria', 'Bulgaria', 'https://sws.geonames.org/732800'],
  ['canary', 'Canary', 'https://sws.geonames.org/2593110'],
  ['catalonia', 'Catalonia', 'https://sws.geonames.org/3336901'],
  ['catalan', 'Catalonia', 'https://sws.geonames.org/3336901'],
  ['croatia', 'Croatia', 'https://sws.geonames.org/3202326'],
  ['cyprus', 'Cyprus', 'https://sws.geonames.org/146669'],
  ['czech', 'Czech Republic', 'https://sws.geonames.org/3077311'],
  ['denmark', 'Denmark', 'https://sws.geonames.org/2623032'],
  ['estonia', 'Estonia', 'https://sws.geonames.org/453733'],
  ['europe', 'Europe', 'https://sws.geonames.org/6255148'],
  ['faroe', 'Faroe Islands', 'https://sws.geonames.org/2622320'],
  ['finland', 'Finland', 'https://sws.geonames.org/660013'],
  ['finnish', 'Finland', 'https://sws.geonames.org/660013'],
  ['france', 'France', 'https://sws.geonames.org/3017382'],
  ['french', 'France', 'https://sws.geonames.org/3017382'],
  ['georgia', 'Georgia', 'https://sws.geonames.org/614540'],
  ['german', 'Germany', 'https://sws.geonames.org/2921044'],
  ['gibraltar', 'Gibraltar', 'https://sws.geonames.org/2411586'],
  ['greece', 'Greece', 'https://sws.geonames.org/390903'],
  ['greek', 'Greece', 'https://sws.geonames.org/390903'],
  ['greenland', 'Greenland', 'https://sws.geonames.org/3425505'],
  ['hungar', 'Hungary', 'https://sws.geonames.org/719819'],
  ['iceland', 'Iceland', 'https://sws.geonames.org/2629691'],
  ['ireland', 'Ireland', 'https://sws.geonames.org/2963597'],
  ['italy', 'Italy', 'https://sws.geonames.org/3175395'],
  ['italia', 'Italy', 'https://sws.geonames.org/3175395'],
  ['kazakh', 'Kazakhstan', 'https://sws.geonames.org/1522867'],
  ['kosovo', 'Kosovo', 'https://sws.geonames.org/831053'],
  ['latvia', 'Latvia', 'https://sws.geonames.org/458258'],
  ['liechten', 'Liechtenstein', 'https://sws.geonames.org/3042058'],
  ['lithua', 'Lithuania', 'https://sws.geonames.org/597427'],
  ['luxembourg', 'Luxembourg', 'https://sws.geonames.org/2960313'],
  ['madeira', 'Madeira', 'https://sws.geonames.org/2593105'],
  ['malta', 'Malta', 'https://sws.geonames.org/2562770'],
  ['moldova', 'Moldova', 'https://sws.geonames.org/617790'],
  ['monaco', 'Monaco', 'https://sws.geonames.org/2993457'],
  ['montenegro', 'Montenegro', 'https://sws.geonames.org/3194884'],
  ['netherlands', 'Netherlands', 'https://sws.geonames.org/2750405'],
  ['dutch', 'Netherlands', 'https://sws.geonames.org/2750405'],
  ['macedon', 'North Macedonia', 'https://sws.geonames.org/718075'],
  ['norway', 'Norway', 'https://sws.geonames.org/3144096'],
  ['poland', 'Poland', 'https://sws.geonames.org/798544'],
  ['polish', 'Poland', 'https://sws.geonames.org/798544'],
  ['portug', 'Portugal', 'https://sws.geonames.org/2264397'],
  ['srpsk', 'Republika Srpska', 'https://sws.geonames.org/3230000'],
  ['romania', 'Romania', 'https://sws.geonames.org/798549'],
  ['russia', 'Russia', 'https://sws.geonames.org/2017370'],
  ['san marino', 'San Marino', 'https://sws.geonames.org/3168068'],
  ['serbia', 'Serbia', 'https://sws.geonames.org/6290252'],
  ['slovak', 'Slovakia', 'https://sws.geonames.org/3057568'],
  ['sloveni', 'Slovenia', 'https://sws.geonames.org/3190538'],
  ['spain', 'Spain', 'https://sws.geonames.org/2510769'],
  ['spanish', 'Spain', 'https://sws.geonames.org/2510769'],
  ['spanish state', 'Spanish State', 'https://sws.geonames.org/2510769'],
  ['svalbard', 'Svalbard', 'https://sws.geonames.org/7521757'],
  ['sweden', 'Sweden', 'https://sws.geonames.org/2661886'],
  ['swedish', 'Sweden', 'https://sws.geonames.org/2661886'],
  ['switzerland', 'Switzerland', 'https://sws.geonames.org/2658434'],
  ['swiss', 'Switzerland', 'https://sws.geonames.org/2658434'],
  ['turkey', 'Türkiye', 'https://sws.geonames.org/298795'],
  ['türkiye', 'Türkiye', 'https://sws.geonames.org/298795'],
  ['ukraine', 'Ukraine', 'https://sws.geonames.org/690791'],
  ['united kingdom', 'United Kingdom', 'https://sws.geonames.org/2635167'],
  ['britain', 'United Kingdom', 'https://sws.geonames.org/2635167'],
  ['british', 'United Kingdom', 'https://sws.geonames.org/2635167']
  ];